### PR TITLE
More GET methods

### PR DESCRIPTION
**Pull request by Sharan-Babu**
Added 4 new functions, 'entity_list', 'entity_info', 'trait_list', 'trait_info'.

### CODE REVIEW

**Comment by Sharan-Babu** [comment]
I also tried implementing one POST method but is not working. I tried the method below and passing ContentType and data separately but did not work on my end. Could you please point where I am going wrong?
~~~
def create_intent(self, intent_name, headers=None, verbose=None):
    """    
    Creates a new intent.

    :param intent_name: name of intent to be created.
    """
    params = {}
    headers = headers or {}
    # if intent_name:
    #     params['name'] = intent_name
    if verbose:
        params['verbose'] = True   
    endpoint = '/intents/name=' + intent_name    
    resp = req(self.logger, self.access_token, 'POST', endpoint, params, headers=headers)
    return resp
~~~

**Comment by Sharan-Babu** [comment]
When I fetch upstream, make new changes and create a new pull request, it shows that the previous commits are also to be merged. I mean, the PR reads 'Sharan-Babu wants to merge 12 commits...' even though I only introduced 4 new commits. Is this something to be fixed? Thanks.

**Comment by chessai** [comment]
> When I fetch upstream, make new changes and create a new pull request, it shows that the previous commits are also to be merged. I mean, the PR reads 'Sharan-Babu wants to merge 12 commits...' even though I only introduced 4 new commits. Is this something to be fixed? Thanks.

It means that git is being used improperly. For now you probably want to rebase and squash, then force push. 

For future reference, you should be checking out a new branch for these features, rather than your own master branch. That's probably contributing to this problem.

**Comment by Sharan-Babu** [comment]
> > When I fetch upstream, make new changes and create a new pull request, it shows that the previous commits are also to be merged. I mean, the PR reads 'Sharan-Babu wants to merge 12 commits...' even though I only introduced 4 new commits. Is this something to be fixed? Thanks.
> 
> It means that git is being used improperly. For now you probably want to rebase and squash, then force push.
> 
> For future reference, you should be checking out a new branch for these features, rather than your own master branch. That's probably contributing to this problem.

Could you merge the PR this time? I can make sure it doesn't happen the next time.

**Comment by Sharan-Babu** [comment]
> I also tried implementing one POST method but is not working. I tried the method below and passing ContentType and data separately but did not work on my end. Could you please point where I am going wrong?
> 
> ```
> def create_intent(self, intent_name, headers=None, verbose=None):
>     """    
>     Creates a new intent.
> 
>     :param intent_name: name of intent to be created.
>     """
>     params = {}
>     headers = headers or {}
>     # if intent_name:
>     #     params['name'] = intent_name
>     if verbose:
>         params['verbose'] = True   
>     endpoint = '/intents/name=' + intent_name    
>     resp = req(self.logger, self.access_token, 'POST', endpoint, params, headers=headers)
>     return resp
> ```

Would also like to have your help with this.

**Comment by chessai** [comment]
What is the error you are getting?

**Comment by chessai** [comment]
Why did you close the PR @Sharan-Babu ?

**Comment by Sharan-Babu** [comment]
Oh, I was thinking of creating a new PR such that we do not have the squash and merge issue.

**Comment by chessai** [comment]
> I was thinking of creating a new PR such that we do not have the squash and merge issue.

Sounds good, thanks!

**Pull request closed without merging**
