### PR TITLE
New style Python class (can be subclassed) and fix no entity # 48

### PR DESCRIPTION
**Pull request by oplatek**
Fixing the issue
https://github.com/wit-ai/pywit/issues/48

and deriving Wit from object `Wit(object)` so it can be subclassed.

### CODE REVIEW

**Comment by patapizza** [comment]
Thanks, the latest version should work.

**Comment by xssChauhan** [comment]
Subclassing is still not possible in python 2.
[`class Wit`](https://github.com/wit-ai/pywit/blob/master/wit/wit.py) instead of `class Wit(object)`

**Comment by patapizza** [comment]
@xssChauhan You are right. Or even better, make a pull request :)

**Comment by xssChauhan** [comment]
I'll do that. What happened to [this commit](https://github.com/wit-ai/pywit/pull/49/commits/0ab8fa48206ba85cd247637a29e5a5e3d18338ed)?

**Pull request closed without merging**
